### PR TITLE
fix: skip conversion for non-identified types

### PR DESCRIPTION
**Pull request by Gaitholabi**
When type extractor cannot identify the type, process and empty array so the SDK doesn't crash.

This fixes the following issue:
```
ERROR: TypeError: array_filter() expects parameter 1 to be array, null given in / supportpal/api-client-php/src/Transformer/IntToBooleanTransformer.php:54 Stack trace: #0
```

### CODE REVIEW

**Comment by bytestream** [comment]
So for the case I fixed yesterday, does the missing `id` attribute actually affect anything (beyond this transformer class)?

**Comment by Gaitholabi** [comment]
> So for the case I fixed yesterday, does the missing `id` attribute actually affect anything (beyond this transformer class)?

don't think so

**Comment by bytestream** [comment]
> 
> 
> > So for the case I fixed yesterday, does the missing `id` attribute actually affect anything (beyond this transformer class)?
> 
> don't think so

If an attribute isn't defined, what would the problems be?

**Comment by Gaitholabi** [comment]
> > > So for the case I fixed yesterday, does the missing `id` attribute actually affect anything (beyond this transformer class)?
> > 
> > 
> > don't think so
> 
> If an attribute isn't defined, what would the problems be?

can't think of any problems beyond this

**Comment by bytestream** [comment]
While the expectation is that all attributes should be defined and have a `serializedname` annotation. I don't think we should be relying on this `TypeError` to find models which are missing attributes. The `TypeError` masks the underlaying issue and makes it somewhat difficult to debug.

I think we take one of two options:
* Throw a meaningful exception when `$types` is `null`
* Convert `null` to `[]` and move on (the approach currently offered in this PR)

I don't mind either so I'll let @Gaitholabi pick. The only thing I'd add is that one is the equivalent of a strict mode, the other is a weak mode. The approach we take really depends on how critical it is that the `serializedname` annotation exists.

**Review by bytestream — DISMISSED** [review]

**Comment by bytestream** [comment]
Opted for
> Convert null to [] and move on (the approach currently offered in this PR)

We don't want it to throw exceptions whenever we add a new attribute to the API response. Instead it would be a feature request that we add that attribute to this library.

**Review by bytestream — APPROVED** [review]

**Pull request merged**
