### PR TITLE
fix(deps): update kevinrob/guzzle-cache-middleware v4

### LINKED ISSUE #160: Upgrade kevinrob/guzzle-cache-middleware
Could we update the following dependencies:

- kevinrob/guzzle-cache-middleware 4.0.0? This resolves some return type issues in previous versions. They did drop PHP 7.2 but to be fair, you guys should too.
- phpstan to 1.4.x
- Support for PHP 8.1

It shouldn't be too painful to upgrade. I ran a quick test on my machine and apart from some deprecations and two errors during tests, it all worked. I have no clue how to solve the failed tests myself.

@bytestream I can PR a failing setup if you like?

### PR DESCRIPTION
**Pull request by ju5t**
Closes #160

### CODE REVIEW

**Comment by bytestream** [comment]
Thanks.

Irritating - there's a phpstan bug...
```
------ ----------------------------------------------------------------------------- 
  Line   test/Cache/CacheableApisTest.php                                             
 ------ ----------------------------------------------------------------------------- 
  275    Reflection error: AnonymousClass8173b1ad570491d4329ae5dfc6ace63a not found.  
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols           
 ------ ----------------------------------------------------------------------------- 
```

**Comment by ju5t** [comment]
Is it possible to ignore this line and skip it for now? Not sure if you're up for it though.

**Comment by bytestream** [comment]
Nope. I've opened https://github.com/phpstan/phpstan/issues/6681

**Comment by bytestream** [comment]
@ju5t I've handled the phpstan and failing tests (https://github.com/supportpal/api-client-php/pull/162), if you rebase this should work now. There's also no need for the changes to `phpstan.neon`

**Comment by bytestream** [comment]
In fact, I've done it in https://github.com/supportpal/api-client-php/pull/164

**Pull request closed without merging**
